config/routes.rb
Rails.application.routes.draw do
root 'sessions#signin'


resources :pictures
resources :sessions
get 'signup'  => 'users#new'
resources :users







delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :uniqueness => true, :presence => true
  has_secure_password
  has_many :pictures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    return true if current_user

    return redirect_to root_path
  end

#


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /pictures
  # GET /pictures.json
    def index
      @pictures = Picture.all
      # @my_array = []
      # @pictures.each do |picture|
      #   @my_array << picture.id

      # url   = "https://www.pinterest.com/search/pins/?q=food"
      # response = HTTParty.get url
      # dom   = Nokogiri::HTML(response.body)
      # @result = []
      # dom.css('._0._3i._45 a img').map do |pin|
      #   img = pin.attr('src')
      #   @result.push(img)
      # end
    end


    def dash

    end


    # GET /pictures/1
    # GET /pictures/1.json
    def show
      # session[:username] = @user.username
      # @username = session[:username]

    end

    # GET /pictures/new
    def new
      @picture = Picture.new
    end

    # GET /pictures/1/edit
    def edit
    end

    # POST /pictures
    # POST /pictures.json
    def create
      @picture = Picture.new(picture_params)
      @picture.user = current_user
      # @picture.user_stamp = session[:id]?????????

      respond_to do |format|
        if @picture.save
          format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
          format.json { render :show, status: :created, location: @picture }
        else
          format.html { render :new }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /pictures/1
    # PATCH/PUT /pictures/1.json
    def update
      respond_to do |format|
        if @picture.update(picture_params)
          format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
          format.json { render :show, status: :ok, location: @picture }
        else
          format.html { render :edit }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /pictures/1
    # DELETE /pictures/1.json
    def destroy
      @picture.destroy
      respond_to do |format|
        format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
        format.json { head :no_content }
      end
    end



    private
      # Use callbacks to share common setup or constraints between actions.
      def set_picture
        @picture = Picture.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def picture_params
        params.require(:picture).permit(:description, :url)
      end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



  def new
end

def create
  @user = User.
          find_by(username: params[:username]).
          try(:authenticate, params[:password])

    return render action: 'signin' unless @user

    session[:user_id] = @user.id
    redirect_to pictures_path
end



def destroy
    session[:user_id] = nil
    redirect_to '/'
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      # session[:username] = @user.username
      redirect_to pictures_path
    else
      # redirect_to '/'
      render :new

    end
  end

  def show
    @user = User.find(params[:id])
  end


  private
    def user_params
      params.
        require(:user).
        permit(:username,
               :password,
                :password_confirmation)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bon Apetit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Allura" rel="stylesheet">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </head>
  <body>
      <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <a class="navbar-brand" href="#"></a><i class="fas fa-utensils"></i>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
          <%= link_to "Home", pictures_path,  :class=> "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
          </li>
          <% if session[:user_id] %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Share Your Food</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#"><%= link_to 'Upload Image', new_picture_path, id: 'upload', remote: true %></a>
              <!-- <a class="dropdown-item" href="#">Upload Video</a>
              <a class="dropdown-item" href="#">Make a Meme</a> -->
            </div>
          </li>
          <li class="nav-item">

          </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, method: "delete", :class=> "nav-link" %>
          </li>
              <% end %>

        </ul>
      </div>
    </nav>
      </div>
  <body>

    <%= yield %>


  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description.to_s, class: 'form-control' %>

  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>
<div class="heading">
  <%= link_to image_tag "logo/logo.jpg" %>
  <h1>Bon Appetit!</h1>
</div>




<% @pictures.each do |pic| %>
  <%= link_to pic do %>
  <%=  image_tag pic.url, :class => "myclass", :style => "border-radius:20px;
  height:250px;width:350px; padding: 5px 0; margin-left: 70px;"  %>

  <% end %>
  <% end %>





<%= render 'modal' %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/new.js.erb
$('.modal-body').html("<%= j render 'form', picture: @picture %>");
$('.modal').modal();

app/views/pictures/nooooo_new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>


<div class="">


  <p class='description'>
    <strong>User:</strong>
    <%= "#{(@current_user.username).capitalize}" %>
    <strong>Description:</strong>
    <%= "#{@picture.description}" %>
  </p>

    <p>

      <%= image_tag @picture.url, class:'show_image' %>
    </p>


</div>


<div class="user_page_bottom">

    <section class="bottom_links">

      <%= link_to 'Edit', edit_picture_path(@picture) %> |
      <%= link_to 'Back', pictures_path %>
      |<%= link_to "#{(@picture.user.username).capitalize}'s collection", @picture.user %>
    </section>

</div>

<%= render 'modal' %>

app/views/users/new.html.erb
<h1>Sign-Up</h1>


<%= form_for @user do |f|%>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <p>
    <%= f.label :username%>
    <%= f.text_field :username%>

  </p>

  <p>
    <%= f.label :password%>
    <%= f.password_field :password%>

  </p>
  <p>
    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation%>

  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Alrealdy a member? Log-In', '/'  %>

app/views/users/show.html.erb
<h1><%= (@user.username).capitalize %>'s Pictures</h1>



  <% @user.pictures.each do |picture| %>
  <p class="description"><strong>Description:</strong><%= picture.description  %></p> <br>
  <%= image_tag(picture.url)%> <br>

<hr>
<% end %>